app:
  server-url: http://localhost:8080
spring:
  datasource:
    url: ${TODAK_DB_URL:jdbc:postgresql://127.0.0.1:5432/todak_dev}
    username: ${TODAK_DB_USER:todak_app}
    password: ${TODAK_DB_PASS:}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    com.sogong.todak: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html