spring:
  application:
    name: todak
  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false

jwt:
  secret: ${JWT_SECRET} # 32바이트 이상의 Base64 또는 일반 문자열
  access-exp-min: 30
  refresh-exp-days: 14

app:
  oauth2:
    redirect-success: http://3.34.99.179:3000/auth/callback
    exchange-code-ttl-seconds: 300
    exchange-code-cleanup-ms: 60000
  security:
    cookie:
      secure: false
  jwt:
    cookie:
      access-name: ACCESS_TOKEN
      refresh-name: REFRESH_TOKEN
      secure: false # 로컬 개발 시 false, 운영 시 true
      same-site: Lax