spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/todak_test
    username: todak_app
    password: TodakApp!2026

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/postgresql
      - classpath:db/seed/test


jwt:
  secret: "test-secret-key-must-be-at-least-32-bytes-long-abcd" # 테스트용 고정 키
  access-exp-min: 30

app:
  kakao:
    admin-key: test-kakao-admin-key
